### ISSUE TITLE
Add a nested folder structure (instead of keeping everything at the root level)

### ISSUE THREAD

**Issue by DilumAluthge** [maleadt/BasePkgEvalReports#1]
Over time, the list of folders in this repository’s root directory is going to become too long to display, and GitHub will give the same “Sorry we had to truncate this directory” message that it gives here: https://github.com/JuliaCI/BaseBenchmarkReports

In order to make the PkgEval reports easier to browse, what do you think of adding some kind of structure instead of storing all folders at the root level.

Maybe something like year/month/day/name_of_job?

cc: @maleadt

**Comment by DilumAluthge** [comment]
Bump @maleadt

**Comment by maleadt** [comment]
Sure, but I'm just mimicking Nanosoldier.jl's existing structure here. I'll have a look.

**Comment by DilumAluthge** [comment]
Yeah we should probably also fix BaseBenchmarkReports at some point. That repository has become impossible to browse.
